version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
  codecov: codecov/codecov@1.2.3 #
  win: circleci/windows@2.4.1

executors:
  with-chrome-and-firefox:
    docker:
      - image: "cypress/browsers:node14.17.0-chrome88-ff89"
    resource_class: medium+

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Commands ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
commands:
  report-coverage:
    description: |
      Store coverage report as an artifact and send it to Codecov service.
    steps:
      - store_artifacts:
          path: coverage
      - run: npx nyc report --reporter=text || true
      - codecov/upload:
          file: coverage/coverage-final.json


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Workflows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
linux-workflow: &linux-workflow
  jobs:
    # Setup
    #  1. Install Cypress
    #  2. Validate types
    #  3. Run server unit-tests
    - cypress/install:
        name: "Setup Linux"
        yarn: true
        executor: with-chrome-and-firefox
        build: "yarn build:ci"
        post-steps:
          - run:
              name: Print machine info ℹ️
              command: yarn cypress info
          - run:
              name: Lint Files
              command: yarn lint
          # - run:
          #     name: Run Unit Tests
          #     command: yarn test:ci


    # Run API tests against backend server
    # - cypress/run:
    #     name: "API Tests"
    #     browser: chrome
    #     spec: cypress/tests/api/*
    #     executor: with-chrome-and-firefox
    #     wait-on: "http://localhost:3000"
    #     yarn: true
    #     start: yarn start:ci
    #     record: true
    #     parallel: true
    #     parallelism: 5
    #     ci-build-id: ${CIRCLE_SHA1:0:8}
    #     group: API
    #     requires:
    #       - Setup Linux
    #     post-steps:
    #       - report-coverage

    # Run E2E tests in Chrome
    - cypress/run:
        name: "UI Tests - Chrome"
        browser: chrome
        spec: cypress/integration/*
        executor: with-chrome-and-firefox
        wait-on: "http://localhost:3000"
        command-prefix: npx percy exec --
        yarn: true
        start: yarn start
        record: true
        parallel: true
        parallelism: 5
        ci-build-id: ${CIRCLE_SHA1:0:8}
        group: "UI - Chrome"
        requires:
          - Setup Linux
        post-steps:
          - report-coverage
          
workflows:
  linux:
    <<: *linux-workflow          
